### ISSUE TITLE
Unable to logon in UAT environment

### ISSUE THREAD

**Issue by JoeriJackers** [Secretarium/MADRec#1]
![screen shot 2018-12-14 at 10 43 44](https://user-images.githubusercontent.com/25148598/49995689-2752a780-ff8d-11e8-9431-a4c7fb4146b8.png)

'Next' button stays greyed out. I've tried (hard) refreshing the page multiple times.

**Comment by bfoing** [comment]
Hi Joeri, sorry we missed your message.

The Next button remained grey because the transaction to set your name was queued but not executed.
This happens when someone else has pushed a very large number of transactions and the network is busy processing them.
At this time last month, we were uploading 1.3M LEIs, and it took several hours.
If you had waited for all queued transaction to be processed, you would, at some point, have had a blue check icon confirming execution, and the Next button would have become enabled.

To give you details in the transaction life cycle:
1. User sends the transaction (icon is a **grey clock**).
2. Node has received and acknowledges (icon becomes a **single grey check**).
Node them passes the transaction to the current master node.
3. Master node acknowledges (this notification is not displayed by the web client).
4. Master node sends the transaction to all nodes (icon becomes **two grey checks**).
5. A majority of nodes have confirmed they have received and queued the transaction (icon becomes **three grey checks**).
At this time you are guaranteed that your transaction will be executed.
6. A majority of nodes have confirmed they have executed the transaction (icon becomes a **blue check**).
This state is final, Secretarium does not use blocks, there is no risk of fork.
